# Copyright 2014 Peter Williams and collaborators.
# Licensed under the MIT license. See LICENSE.md for details.

builddir = build
python = python
texdist = tl2013
pdfjsversion = 1.0.712
yuiversion = 2.4.8

default: all


# Source files for the main JavaScript apps.

genlists = \
  commands.txt \
  namedparams.txt

# Non-TeX-specific low-level utilities
sharedjs = \
  src/preamble.js \
  src/format.js \
  src/inflate.js \
  src/jsonparse.js \
  src/zipreader.js

# Basic classes, constants
sharedjs += \
  src/constants.js \
  src/str-utils.js \
  src/numerics.js \
  src/base-classes.js \
  src/values.js \
  src/valrefs.js \
  src/token.js

# I/O infrastructure
sharedjs += \
  src/linebuffer.js \
  src/ordsource.js \
  src/inputstack.js \
  src/iostack.js \
  src/bundle.js \
  src/document-archive.js

# High-level features
sharedjs += \
  src/modes.js \
  src/registers.js \
  src/parameters.js \
  src/conditionals.js \
  src/fonts.js \
  src/listables.js \
  src/boxes.js \
  src/paragraphs.js \
  src/inserts.js \
  src/math.js \
  src/align.js \
  src/page-builder.js \
  src/command-classes.js \
  src/command-impls.js \
  $(builddir)/intermediates/engine-helpers.js \
  src/engine.js \
  src/ship-target.js \
  src/html-translate-target.js

$(builddir)/intermediates/%-helpers.js: \
dev-scripts/preprocess.py src/%-helpers-tmpl.js $(genlists) \
| $(builddir)/intermediates
	$(python) $< src/$*-helpers-tmpl.js $@


# The first version of Webtex that we build is the Node.js version. We require
# this to create the ".dump.json" files that will go into the bundle.

nodejs = \
  src/node-io.js \
  src/node-api.js

$(builddir)/node-webtex.js: \
dev-scripts/preprocess.py src/node-wrapper.js $(preamble) $(sharedjs) $(nodejs) \
| $(builddir)/intermediates
	$(python) $^ $@

primaries += $(builddir)/node-webtex.js


# Here we build the bundle and those .dump.json files that it requires. TODO:
# Feeling dissatisfied with the naming scheme.

bundleextras = \
  $(builddir)/latex.dump.json

$(builddir)/latex.dump.json: \
dev-scripts/dump-format.js $(builddir)/node-webtex.js texpatches/$(texdist)/latex.ltx.post \
| $(builddir)
	node $< $(builddir)/node-webtex.js texpatches/$(texdist)/ latex.ltx $@

$(builddir)/plain.dump.json: \
dev-scripts/dump-format.js $(builddir)/node-webtex.js \
| $(builddir)
	node $< $(builddir)/node-webtex.js texpatches/$(texdist)/ plain.tex $@

$(builddir)/dev/newest-bundle.zip $(builddir)/dev/glyph-encoding.json: \
dev-scripts/make-bundle.py packages.txt mapfiles.txt $(bundleextras) \
| $(builddir)/dev
	$(python) $< packages.txt mapfiles.txt texcache $(builddir)/dev texpatches $(bundleextras)


# Next up is the browser version of Webtex. This is split into two parts: the
# "backend", which contains the TeX engine and does all the processing, and
# the "frontend", which just renders the backend's output. The backend is run
# as a Web Worker thread. It and the Node.js version are 99% the same, just
# with different I/O backends (local files vs. web requests) and exposing
# their APIs in different ways.

backendjs = \
  src/browser-io.js \
  src/backend-api.js

$(builddir)/dev/webtex-backend.js: \
dev-scripts/preprocess.py src/backend-wrapper.js $(sharedjs) $(backendjs) \
| $(builddir)/dev
	$(python) $^ $@

primaries += $(builddir)/dev/webtex-backend.js
devfiles += $(builddir)/dev/webtex-backend.js

# The frontend, which drives the backend and renders its output into the DOM.
# This can only be built after the bundle, because the frontend code embeds
# the list of glyph identifiers, which is generated as font files in the
# bundle are processed. The frontend does *not* include all of the code for
# the TeX engine; it only has code to display the intermediate ("chrome") data
# format generated by the backend.

frontendjs = \
  src/preamble.js \
  src/format.js \
  src/master-object.js \
  $(builddir)/intermediates/frontend-glyph-helper.js \
  src/type1-font.js \
  src/dom-renderer.js

$(builddir)/dev/webtex-frontend.js: \
dev-scripts/preprocess.py src/frontend-wrapper.js $(frontendjs) \
| $(builddir)/dev
	$(python) $^ $@

primaries += $(builddir)/dev/webtex-frontend.js
devfiles += $(builddir)/dev/webtex-frontend.js

$(builddir)/intermediates/frontend-glyph-helper.js: \
dev-scripts/preprocess.py src/frontend-glyph-helper-tmpl.js $(builddir)/dev/glyph-encoding.json \
| $(builddir)/intermediates
	$(python) $^ $@


# We use an internal copy of PDF.js to render PDF figures. These rules
# download and unpack it.

pdfjs_unzip_stamp = $(builddir)/pdfjs/build/pdf.js

$(builddir)/pdfjs-$(pdfjsversion)-dist.zip: \
| $(builddir)
	curl -L https://github.com/mozilla/pdf.js/releases/download/v$(pdfjsversion)/pdfjs-$(pdfjsversion)-dist.zip >$@

$(pdfjs_unzip_stamp): \
$(builddir)/pdfjs-$(pdfjsversion)-dist.zip \
| $(builddir)
	rm -rf $(builddir)/pdfjs
	mkdir -p $(builddir)/pdfjs
	cd $(builddir)/pdfjs && unzip -q -DD ../pdfjs-$(pdfjsversion)-dist.zip

$(builddir)/dev/compatibility.js: \
$(pdfjs_unzip_stamp) \
| $(builddir)/dev
	cd $(builddir)/dev && ln -s ../pdfjs/web/compatibility.js

$(builddir)/dev/pdf.js: \
$(pdfjs_unzip_stamp) \
| $(builddir)/dev
	cd $(builddir)/dev && ln -s ../pdfjs/build/pdf.js

$(builddir)/dev/pdf.worker.js: \
$(pdfjs_unzip_stamp) \
| $(builddir)/dev
	cd $(builddir)/dev && ln -s ../pdfjs/build/pdf.worker.js

primaries += $(pdfjs_unzip_stamp)
devfiles += \
  $(builddir)/dev/compatibility.js \
  $(builddir)/dev/pdf.js \
  $(builddir)/dev/pdf.worker.js


# Here we link the chrome data files into the dev directory

$(builddir)/dev/%: chrome/% \
| $(builddir)/dev
	cp $^ $@

devfiles += $(patsubst chrome/%,$(builddir)/dev/%,$(wildcard chrome/*))


# These rules produce HTML drivers for the local development environment

$(builddir)/dev/%.html: \
demo/drivers/%.html.in \
$(builddir)/dev/newest-bundle.zip \
| $(builddir)
	sed -e "s|@BUNDLE@|newest-bundle.zip|g" \
	    -e "s|@CHROME@|.|g" $< >$@.new \
	 && mv -f $@.new $@

devfiles += $(patsubst demo/drivers/%.in,$(builddir)/dev/%,$(wildcard demo/drivers/*.in))


# These rules produce demo files for the installable distribution.

$(builddir)/dev/brockton.zip: \
| $(builddir)/dev
	zip -j $@ demo/brockton/*

$(builddir)/dev/brockton.json: \
webtex \
$(builddir)/node-webtex.js \
| $(builddir)/dev
	./webtex -n3 -T chrome demo/brockton/paper.tex >$@.new && mv -f $@.new $@

$(builddir)/%.html: \
demo/drivers/%.html.in \
$(builddir)/dev/newest-bundle.zip \
| $(builddir)
	sed -e "s/@BUNDLE@/`readlink $(builddir)/dev/newest-bundle.zip`/g" $< >$@.new \
	 && mv -f $@.new $@


# These rules produce HTML drivers that will be included in the distribution Zip.

$(builddir)/intermediates/distrib-%.html: \
demo/drivers/%.html.in \
$(builddir)/dev/newest-bundle.zip \
| $(builddir)/intermediates
	sed -e "s|@BUNDLE@|`readlink $(builddir)/dev/newest-bundle.zip`|g" \
	    -e "s|@CHROME@|.|g" $< >$@.new \
	 && mv -f $@.new $@



# Finally, the rule to generate an installable distribution. You can unzip
# this and run your own copy of Webtex, either on a local machine with a
# localhost HTTP server, or by copying to your own server. The demo files
# reference a bundle on webtex.newton.cx rather than including their own copy.

$(builddir)/distrib.zip: \
$(builddir)/webtex-backend.js \
$(builddir)/webtex-frontend.js \
$(pdfjs_unzip_stamp) \
$(builddir)/brockton.zip \
$(builddir)/brockton.json \
demo/drivers/local-server.js \
$(builddir)/render-preparsed.html \
$(builddir)/parse-and-render.html \
Makefile \
| $(builddir)
	@w=`mktemp -d $(builddir)/distrib.XXXXXXXX`; \
	dstem=distrib-$(texdist)-`date +%Y%m%d`.zip ; \
	rm -f $(builddir)/$$dstem $@ ; \
	cp $(builddir)/webtex-backend.js $(builddir)/webtex-frontend.js \
	   $(builddir)/pdfjs/build/pdf*.js $(builddir)/pdfjs/web/compatibility.js \
	   $(builddir)/brockton.zip $(builddir)/brockton.json \
	   $(builddir)/render-preparsed.html $(builddir)/parse-and-render.html \
	   demo/drivers/local-server.js demo/drivers/README.md $$w ; \
	(cd $$w && zip ../$$dstem *) ; \
	(cd $(builddir) && ln -s $$dstem `basename $@`) ; \
	rm -rf $$w ; \
	echo Created $(builddir)/$$dstem

distrib: $(builddir)/distrib.zip


# Minifying. Not something I've explored much so far.

minify = java -jar build/yuicompressor-$(yuiversion).jar

$(builddir)/yuicompressor-$(yuiversion).jar: \
| $(builddir)
	curl -L https://github.com/yui/yuicompressor/releases/download/v$(yuiversion)/yuicompressor-$(yuiversion).jar >$@

%.min.js: %.js build/yuicompressor-$(yuiversion).jar
	$(minify) $< >$@.new && mv -f $@.new $@


# Testing. TODO: :-(

test:
	@echo I am a bad person and there are no tests.


# Utility

server:
	node dev-scripts/testing-server.js $(builddir)/dev &


# Generic helpers

all: $(primaries)

dev: $(devfiles)

$(builddir):
	mkdir -p $@

$(builddir)/intermediates:
	mkdir -p $@

$(builddir)/dev:
	mkdir -p $@

clean:
	-rm -rf $(builddir)

.PHONY: all clean default dev distrib server test
